version: '3.8'
services:
  web:
    build: ./web
    platform: linux/amd64
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./web/build:/web/build
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_PASSWORD: foobar
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
      POSTGRES_PORT: 5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./data/sql/10_postgis.sh:/docker-entrypoint-initdb.d/10_postgis.sh
      - ./data/sql/20_database.sql:/docker-entrypoint-initdb.d/20_database.sql
    ports:
      - "5432:5432"
